### ISSUE TITLE
Error when using fromFile()

### ISSUE THREAD

**Issue by daniyalkhan2000** [IonicaBizau/ama#34]
Not sure how to fix the error but this is what I get

2018-07-06T14:24:37.694668+00:00 app[worker.1]: TypeError: url.indexOf is not a function
2018-07-06T14:24:37.694673+00:00 app[worker.1]:     at getPixels (/app/node_modules/get-pixels/node-pixels.js:136:17)
2018-07-06T14:24:37.694675+00:00 app[worker.1]:     at /app/node_modules/face-detectify/lib/index.js:64:17
2018-07-06T14:24:37.694677+00:00 app[worker.1]:     at new Promise (<anonymous>)
2018-07-06T14:24:37.694678+00:00 app[worker.1]:     at Function.fromFile (/app/node_modules/face-detectify/lib/index.js:63:20)
2018-07-06T14:24:37.694679+00:00 app[worker.1]:     at Jimp.<anonymous> (/app/commands/faceshit/diofaces.js:117:47)
2018-07-06T14:24:37.694681+00:00 app[worker.1]:     at WriteStream.<anonymous> (/app/node_modules/jimp/index.js:2556:23)
2018-07-06T14:24:37.694682+00:00 app[worker.1]:     at emitNone (events.js:111:20)
2018-07-06T14:24:37.694683+00:00 app[worker.1]:     at WriteStream.emit (events.js:208:7)
2018-07-06T14:24:37.694685+00:00 app[worker.1]:     at finishMaybe (_stream_writable.js:614:14)
2018-07-06T14:24:37.694686+00:00 app[worker.1]:     at afterWrite (_stream_writable.js:465:3)

**Comment by daniyalkhan2000** [comment]
Apologies, it was an issue with my code
